class LanguageModel {
  final String name;
  final String nativeName;
  final String locale;

  const LanguageModel({
    required this.name,
    required this.nativeName,
    required this.locale,
  });

  String str(String key) {
    return LanguageConstants.homeTranslations[name]?[key] ?? LanguageConstants.homeTranslations['English']![key]!;
  }
}

class LanguageConstants {
  static const List<LanguageModel> supportedLanguages = [
    LanguageModel(name: 'English', nativeName: 'English', locale: 'en_IN'),
    LanguageModel(name: 'Hindi', nativeName: 'हिन्दी', locale: 'hi_IN'),
    LanguageModel(name: 'Marathi', nativeName: 'मराठी', locale: 'mr_IN'),
    LanguageModel(name: 'Tamil', nativeName: 'தமிழ்', locale: 'ta_IN'),
    LanguageModel(name: 'Telugu', nativeName: 'తెలుగు', locale: 'te_IN'),
    LanguageModel(name: 'Bengali', nativeName: 'বাংলা', locale: 'bn_IN'),
    LanguageModel(name: 'Gujarati', nativeName: 'ગુજરાતી', locale: 'gu_IN'),
    LanguageModel(name: 'Kannada', nativeName: 'ಕನ್ನಡ', locale: 'kn_IN'),
    LanguageModel(name: 'Malayalam', nativeName: 'മലയാളം', locale: 'ml_IN'),
    LanguageModel(name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', locale: 'pa_IN'),
    LanguageModel(name: 'Odia', nativeName: 'ଓଡ଼ିଆ', locale: 'or_IN'),
  ];
  
  static const Map<String, Map<String, String>> homeTranslations = {
    'English': {
      'select_language': 'Select Language',
      'language': 'Language',
      'namaste': 'Namaste! \nHow can I help you today?',
      'select_option': 'Select an option below to begin.',
      'upload_photo': 'Upload Loan Photo',
      'scan_subtitle': 'SCAN DOCUMENT OR SCREENSHOT',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'speak_to_me': 'Speak to Me',
      'speak_subtitle': 'VOICE-AIDED LOAN AUDIT',
      'private_offline': 'Your data is private and offline.',
      'analyzing': 'Analyzing...',
      'error': 'Analysis Error',
      'ok': 'OK',
      'consent_title': 'Share Anonymized Data?',
      'consent_msg': 'To help protect other vulnerable borrowers, we can anonymously record the bias type and interest rate deviation of this loan. No personal data or actual text from your loan is ever saved.',
      'consent_no': 'No, keep private',
      'consent_yes': 'Yes, share securely',
      'btn_replay_audio': 'Replay Audio',
      'onboarding_title_1': 'Welcome to LoanLens',
      'onboarding_subtitle_1': 'Your AI-powered guardian against predatory lending practices.',
      'onboarding_title_2': 'Snap or Speak',
      'onboarding_subtitle_2': 'Upload a loan document screenshot or speak to our AI to analyze the terms.',
      'onboarding_title_3': 'Get Your Score',
      'onboarding_subtitle_3': 'Receive a fairness rating and clear guidance on hidden risks.',
      'onboarding_start_button': 'Protect Me Now',
      'onboarding_next_button': 'Next',
      'onboarding_skip_button': 'Skip',
      'error_network_title': 'Guardian Unreachable',
      'error_network_msg': 'Your data is safe, but we need a brief connection to the cloud for full analysis. Please check your data or Wi-Fi.',
      'btn_retry': 'Try Again',
      'btn_home': 'Go Back Home',
      'choose_language': 'Choose your language',
      'guardian_active': 'GUARDIAN ACTIVE',
      'analyzing_caps': 'ANALYZING',
      'listening': 'Listening...',
      'speak_now': 'Speak now...',
      'finish': 'Finish',
      'cancel': 'Cancel',
      'history_title': 'The Record',
      'history_empty_title': 'The Record is Clear',
      'history_empty_body': 'No anonymized predatory records have been reported yet. Be the first to analyze a risky loan and protect your community from digital debt traps!',
      'history_start_audit': 'Start First Audit',
      'history_bias': 'Bias Type:',
      'history_deviation': 'Deviation:',
      'history_score_prefix': 'Score:',
      'history_unknown_date': 'Unknown date',
      'history_unknown_app': 'Unknown App',
      'all_clear': 'All Clear',
      'all_clear_msg': 'No predatory terms detected in this audit.',
      'share_title': '🛡️ LoanLens Guardian Report',
    },
    'Hindi': {
      'select_language': 'भाषा चुनें',
      'language': 'भाषा',
      'namaste': 'नमस्ते! \nमैं आपकी कैसे मदद कर सकता हूँ?',
      'select_option': 'शुरू करने के लिए नीचे एक विकल्प चुनें।',
      'upload_photo': 'लोन की फोटो अपलोड करें',
      'scan_subtitle': 'दस्तावेज़ या स्क्रीनशॉट स्कैन करें',
      'camera': 'कैमरा',
      'gallery': 'गैलरी',
      'speak_to_me': 'मुझसे बात करें',
      'speak_subtitle': 'वॉयस-एडेड लोन ऑडिट',
      'private_offline': 'आपका डेटा निजी और ऑफ़लाइन है।',
      'analyzing': 'विश्लेषण हो रहा है...',
      'error': 'त्रुटि',
      'ok': 'ठीक है',
      'consent_title': 'डेटा साझा करें?',
      'consent_msg': 'अन्य कमजोर उधारकर्ताओं की सुरक्षा के लिए, हम इस ऋण पैटर्न को गुमनाम रूप से रिकॉर्ड करेंगे। आपका कोई भी व्यक्तिगत डेटा सहेजा नहीं जाएगा।',
      'consent_no': 'नहीं, निजी रखें',
      'consent_yes': 'हाँ, सुरक्षित रूप से साझा करें',
      'btn_replay_audio': 'ऑडियो फिर से सुनें',
      'onboarding_title_1': 'LoanLens में आपका स्वागत है',
      'onboarding_subtitle_1': 'शोषणकारी ऋण प्रथाओं के खिलाफ आपका एआई-संचालित रक्षक।',
      'onboarding_title_2': 'फोटो लें या बोलें',
      'onboarding_subtitle_2': 'ऋण दस्तावेज का स्क्रीनशॉट अपलोड करें या शर्तों के विश्लेषण के लिए हमारे एआई से बात करें।',
      'onboarding_title_3': 'अपना स्कोर प्राप्त करें',
      'onboarding_subtitle_3': 'छिপে हुए जोखिमों पर निष्पक्षता रेटिंग और स्पष्ट मार्गदर्शन प्राप्त करें।',
      'onboarding_start_button': 'अभी सुरक्षित करें',
      'onboarding_next_button': 'अगला',
      'onboarding_skip_button': 'छोड़ें',
      'error_network_title': 'संरक्षक से संपर्क नहीं हुआ',
      'error_network_msg': 'आपका डेटा सुरक्षित है, लेकिन विश्लेषण के लिए इंटरनेट की आवश्यकता है। कृपया अपना डेटा या वाई-फाई जांचें।',
      'btn_retry': 'फिर से प्रयास करें',
      'btn_home': 'होम पर जाएं',
      'choose_language': 'अपनी भाषा चुनें',
      'guardian_active': 'गार्जियन सक्रिय',
      'analyzing_caps': 'विश्लेषण हो रहा है',
      'listening': 'सुन रहा हूँ...',
      'speak_now': 'अब बोलें...',
      'finish': 'समाप्त',
      'cancel': 'रद्द करें',
      'history_title': 'रिकॉर्ड',
      'history_empty_title': 'रिकॉर्ड खाली है',
      'history_empty_body': 'अभी तक कोई शोषणकारी रिकॉर्ड रिपोर्ट नहीं किया गया है। जोखिम भरे ऋण का विश्लेषण करने वाले पहले व्यक्ति बनें!',
      'history_start_audit': 'पहला ऑडिट शुरू करें',
      'history_bias': 'पक्षपात प्रकार:',
      'history_deviation': 'वियालन:',
      'history_score_prefix': 'स्कोर:',
      'history_unknown_date': 'अज्ञात तिथि',
      'history_unknown_app': 'अज्ञात ऐप',
      'all_clear': 'सब ठीक है',
      'all_clear_msg': 'इस ऑडिट में कोई शोषणकारी शर्तें नहीं मिलीं।',
      'share_title': '🛡️ LoanLens गार्जियन रिपोर्ट',
    },
    'Marathi': {
      'select_language': 'भाषा निवडा',
      'language': 'भाषा',
      'namaste': 'नमस्कार! \nमी तुमची कशी मदत करू शकतो?',
      'select_option': 'सुरू करण्यासाठी खालील पर्याय निवडा.',
      'upload_photo': 'कर्जाचा फोटो अपलोड करा',
      'scan_subtitle': 'दस्तऐवज किंवा स्क्रीनशॉट स्कॅन करा',
      'camera': 'कॅमेरा',
      'gallery': 'गॅलरी',
      'speak_to_me': 'माझ्याशी बोला',
      'speak_subtitle': 'व्हॉइस-एडेड लोन ऑडिट',
      'private_offline': 'तुमचा डेटा खाजगी आणि ऑफलाइन आहे.',
      'analyzing': 'विश्लेषण करत आहे...',
      'error': 'त्रुटी',
      'ok': 'ठीक आहे',
      'consent_title': 'डेटा सामायिक करायचा?',
      'consent_msg': 'इतर असुरक्षित कर्जदारांचे संरक्षण करण्यासाठी, आम्ही कर्जाचा तपशील अनामिकपणे नोंदवू शकतो।',
      'consent_no': 'नाही, खाजगी ठेवा',
      'consent_yes': 'होय, सुरक्षितपणे साماयिक करा',
      'btn_replay_audio': 'ऑडिओ पुन्हा ऐका',
      'error_network_title': 'संरक्षकाशी संपर्क तुटला',
      'error_network_msg': 'तुमचा डेटा सुरक्षित आहे, पण विश्लेෂणासाठी इंटरनेट आवश्यक आहे।',
      'btn_retry': 'पुन्हा प्रयत्न करा',
      'btn_home': 'होम वर जा',
      'choose_language': 'तुमची भाषा निवडा',
      'guardian_active': 'संरक्षक सक्रिय',
      'analyzing_caps': 'विश्लेषण सुरू आहे',
      'listening': 'ऐकत आहे...',
      'speak_now': 'आता बोला...',
      'finish': 'पूर्ण करा',
      'cancel': 'रद्द करा',
      'history_title': 'विक्रम',
      'history_empty_title': 'रेकॉर्ड स्पष्ट आहे',
      'history_empty_body': 'अद्याप कोणतेही शोषणकारी रेकॉर्ड नाहीत। पहिले ऑडिट सुरू करा!',
      'history_start_audit': 'पहिले ऑडिट सुरू करा',
      'history_bias': 'पक्षपात प्रकार:',
      'history_deviation': 'वियालन:',
      'history_score_prefix': 'स्कोर:',
      'history_unknown_date': 'अज्ञात तारीख',
      'history_unknown_app': 'अज्ञात अॅप',
      'all_clear': 'सर्व स्पष्ट',
      'all_clear_msg': 'या ऑडिटमध्ये कोणत्याही शोषणकारी अटी आढळल्या नाहीत।',
      'share_title': '🛡️ LoanLens संरक्षक अहवाल',
    },
    'Tamil': {
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'language': 'மொழி',
      'namaste': 'வணக்கம்! \nநான் உங்களுக்கு எப்படி உதவ முடியும்?',
      'select_option': 'தொடங்க கீழே உள்ள விருப்பத்தை தேர்ந்தெடுக்கவும்.',
      'upload_photo': 'கடன் புகைப்படத்தை பதிவேற்றவும்',
      'scan_subtitle': 'ஆவணம் அல்லது ஸ்கிரீன்ஷாட்டை ஸ்கேன் செய்யவும்',
      'camera': 'கேமரா',
      'gallery': 'கேலரி',
      'speak_to_me': 'என்னிடம் பேசுங்கள்',
      'speak_subtitle': 'குரல் வழி கடன் தணிக்கை',
      'private_offline': 'உங்கள் தரவு தனிப்பயனானது.',
      'analyzing': 'பகுப்பாய்வு தொடர்கிறது...',
      'error': 'பிழை',
      'ok': 'சரி',
      'consent_title': 'தரவைப் பகிரவா?',
      'consent_msg': 'மற்றவர்களைப் பாதுகாக்க, இந்த கடனை அநாமதேயமாக பதிவு செய்யலாம்.',
      'consent_no': 'இல்லை',
      'consent_yes': 'ஆம்',
      'btn_replay_audio': 'மீண்டும் இயக்கு',
      'error_network_title': 'பாதுகாவலரை அணுக முடியவில்லை',
      'error_network_msg': 'பகுப்பாய்விற்கு இணைய வசதி தேவை.',
      'btn_retry': 'மீண்டும் முயற்சிக்கவும்',
      'btn_home': 'முகப்புக்குச் செல்லவும்',
      'choose_language': 'உங்கள் மொழியைத் தேர்வு செய்யவும்',
      'guardian_active': 'பாதுகாவலர் செயலில் உள்ளார்',
      'analyzing_caps': 'பகுப்பாய்வு செய்கிறது',
      'listening': 'கவனித்துக் கொண்டிருக்கிறது...',
      'speak_now': 'இப்போது பேசுங்கள்...',
      'finish': 'முடி',
      'cancel': 'ரத்து செய்',
      'history_title': 'பதிவு',
      'history_empty_title': 'பதிவு தெளிவாக உள்ளது',
      'history_empty_body': 'இதுவரை எந்த சுரண்டல் பதிவுகளும் இல்லை. முதல் தணிக்கையைத் தொடங்குங்கள்!',
      'history_start_audit': 'முதல் தணிக்கையைத் தொடங்குங்கள்',
      'history_bias': 'சார்பு வகை:',
      'history_deviation': 'விலகல்:',
      'history_score_prefix': 'மதிப்பெண்:',
      'history_unknown_date': 'தெரியாத தேதி',
      'history_unknown_app': 'தெரியாத பயன்பாடு',
      'all_clear': 'எல்லாம் சரி',
      'all_clear_msg': 'இந்த தணிக்கையில் எந்த விதிமீறல்களும் கண்டறியப்படவில்லை.',
      'share_title': '🛡️ LoanLens பாதுகாவலர் அறிக்கை',
    },
    'Telugu': {
      'select_language': 'భాషను ఎంచుకోండి',
      'language': 'భాష',
      'namaste': 'నమస్తే! \nనేను మీకు ఎలా సహాయపడగలను?',
      'select_option': 'ప్రారంభించడానికి దిగువ ఎంపికను ఎంచుకోండి.',
      'upload_photo': 'రుణ ఫోటో అప్‌లోడ్ చేయండి',
      'scan_subtitle': 'డాక్యుమెంట్ లేదా స్క్రీన్‌షాట్‌ని స్కాన్ చేయండి',
      'camera': 'కెమెరా',
      'gallery': 'గ్యాలరీ',
      'speak_to_me': 'నాతో మాట్లాడండి',
      'speak_subtitle': 'వాయిస్-ఎయిడెడ్ లోన్ ఆడిట్',
      'private_offline': 'మీ డేటా ప్రైవేట్.',
      'analyzing': 'విశ్లేషిస్తోంది...',
      'error': 'లోపం',
      'ok': 'సరే',
      'consent_title': 'డేటాను భాగస్వామ్యం చేయాలా?',
      'consent_msg': 'ఇతర రుణగ్రహీతలను రక్షించడానికి, మేము ఈ డేటాను అనామకంగా రికార్డ్ చేయవచ్చు.',
      'consent_no': 'లేదు',
      'consent_yes': 'అవును',
      'btn_replay_audio': 'మళ్లీ ప్లే చేయండి',
      'error_network_title': 'గార్డియన్‌ను సంప్రదించలేకపోయాము',
      'error_network_msg': 'విశ్లేషణ కోసం ఇంటర్నెట్ అవసరం.',
      'btn_retry': 'మళ్లీ ప్రయత్నించండి',
      'btn_home': 'హోమ్‌కు వెళ్లండి',
      'choose_language': 'మీ భాషను ఎంచుకోండి',
      'guardian_active': 'గార్డియన్ సక్రియంగా ఉంది',
      'analyzing_caps': 'విశ్లేషిస్తోంది',
      'listening': 'వింటున్నారు...',
      'speak_now': 'ఇప్పుడు మాట్లాడండి...',
      'finish': 'పూర్తి చేయండి',
      'cancel': 'రద్దు చేయండి',
      'history_title': 'రికార్డు',
      'history_empty_title': 'రికార్డు క్లియర్‌గా ఉంది',
      'history_empty_body': 'ఇంకా ఎటువంటి దోపిడీ రికార్డులు లేవు. మొదటి ఆడిట్‌ను ప్రారంభించండి!',
      'history_start_audit': 'మొదటి ఆడిట్‌ను ప్రారంభించండి',
      'history_bias': 'పక్షపాత రకం:',
      'history_deviation': 'విచలనం:',
      'history_score_prefix': 'స్కోరు:',
      'history_unknown_date': 'తెలియని తేదీ',
      'history_unknown_app': 'తెలియని యాప్',
      'all_clear': 'అంతా బాగుంది',
      'all_clear_msg': 'ఈ ఆడిట్‌లో ఎటువంటి దోపిడీ నిబంధనలు గుర్తించబడలేదు.',
      'share_title': '🛡️ LoanLens గార్డియన్ నివేదిక',
    },
    'Bengali': {
      'select_language': 'ভাষা নির্বাচন করুন',
      'language': 'ভাষা',
      'namaste': 'নমস্তে! \nআমি আপনাকে কীভাবে সাহায্য করতে পারি?',
      'select_option': 'শুরু করতে নীচের একটি বিকল্প নির্বাচন করুন।',
      'upload_photo': 'ঋণের ছবি আপলোড করুন',
      'scan_subtitle': 'ডকুমেন্ট বা স্ক্রিনশট স্ক্যান করুন',
      'camera': 'ক্যামেরা',
      'gallery': 'গ্যালারি',
      'speak_to_me': 'আমার সাথে কথা বলুন',
      'speak_subtitle': 'ভয়েস-এইডেড লোন অডিট',
      'private_offline': 'আপনার তথ্য নিরাপদ।',
      'analyzing': 'বিশ্লেষণ করা হচ্ছে...',
      'error': 'ভুল',
      'ok': 'ঠিক আছে',
      'consent_title': 'ডেটা শেয়ার করবেন?',
      'consent_msg': 'অন্যদের রক্ষা করতে সাহায্য করার জন্য, আমরা বেনামে এই ঋণটি রেকর্ড করতে পারি।',
      'consent_no': 'না',
      'consent_yes': 'হ্যাঁ',
      'btn_replay_audio': 'আবার চালান',
      'error_network_title': 'গার্ডিয়ান পাওয়া যাচ্ছে না',
      'error_network_msg': 'বিশ্লেষণের জন্য ইন্টারনেট সংযোগ প্রয়োজন।',
      'btn_retry': 'আবার চেষ্টা করুন',
      'btn_home': 'হোমে ফিরে যান',
      'choose_language': 'আপনার ভাষা চয়ন করুন',
      'guardian_active': 'গার্ডিয়ান সক্রিয়',
      'analyzing_caps': 'বিশ্লেষণ করছে',
      'listening': 'শুনছি...',
      'speak_now': 'এখন বলুন...',
      'finish': 'শেষ করুন',
      'cancel': 'বাতিল করুন',
      'history_title': 'রেকর্ড',
      'history_empty_title': 'রেকর্ড পরিষ্কার',
      'history_empty_body': 'এখনও কোনো শোষণমূলক রেকর্ড পাওয়া যায়নি। প্রথম অডিট শুরু করুন!',
      'history_start_audit': 'প্রথম অডিট শুরু করুন',
      'history_bias': 'পক্ষপাতিত্বের ধরন:',
      'history_deviation': 'বিচ্যুতি:',
      'history_score_prefix': 'স্কোর:',
      'history_unknown_date': 'অজানা তারিখ',
      'history_unknown_app': 'অজানা অ্যাপ',
      'all_clear': 'সব পরিষ্কার',
      'all_clear_msg': 'এই অডিটে কোনো শোষণমূলক শর্ত পাওয়া যায়নি।',
      'share_title': '🛡️ LoanLens গার্ডিয়ান রিপোর্ট',
    },
    'Gujarati': {
      'select_language': 'ભાષા પસંદ કરો',
      'language': 'ભાષા',
      'namaste': 'નમસ્તે! \nહું તમારી કેવી રીતે મદદ કરી શકું?',
      'select_option': 'પ્રારંભ કરવા માટે નીચેનો વિકલ્પ પસંદ કરો.',
      'upload_photo': 'લોનનો ફોટો અપલોડ કરો',
      'scan_subtitle': 'દસ્તાવેજ અથવા સ્ક્રીનશોટ સ્કેન કરો',
      'camera': 'કેમેરા',
      'gallery': 'ગૅલેરી',
      'speak_to_me': 'મારી સાથે વાત કરો',
      'speak_subtitle': 'વોઈસ-એઈડેડ લોન ઓડિટ',
      'private_offline': 'તમારો ડેટા ખાનગી છે.',
      'analyzing': 'વિશ્લેષણ ચાલી રહ્યું છે...',
      'error': 'ભૂલ',
      'ok': 'બરાબર',
      'consent_title': 'ડેટા શેર કરવો છે?',
      'consent_msg': 'અન્ય લોકોને બચાવવા માટે, અમે આ ડેટાને અનામી રૂપે રેકોર્ડ કરી શકીએ છીએ।',
      'consent_no': 'ના',
      'consent_yes': 'હા',
      'btn_replay_audio': 'ઑડિઓ ફરીથી ચલાવો',
      'error_network_title': 'રક્ષક સુલભ નથી',
      'error_network_msg': 'વિશ્લેષણ માટે ઇન્ટરનેટની જરૂર છે.',
      'btn_retry': 'ફરીથી પ્રયત્ન કરો',
      'btn_home': 'હોમ પર જાઓ',
      'choose_language': 'તમારી ભાષા પસંદ કરો',
      'guardian_active': 'ગાર્ડિયન સક્રિય છે',
      'analyzing_caps': 'વિશ્લેષણ કરી રહ્યું છે',
      'listening': 'સાંભળી રહ્યા છીએ...',
      'speak_now': 'હવે બોલો...',
      'finish': 'પૂર્ણ કરો',
      'cancel': 'રદ કરો',
      'history_title': 'રેકોર્ડ',
      'history_empty_title': 'રેકોર્ડ સ્પષ્ટ છે',
      'history_empty_body': 'હજી સુધી કોઈ શોષણખોર રેકોર્ડ નથી। પહેલું ઓડિટ શરૂ કરો!',
      'history_start_audit': 'પહેલું ઓડિટ શરૂ કરો',
      'history_bias': 'પક્ષપાત પ્રકાર:',
      'history_deviation': 'વિચલન:',
      'history_score_prefix': 'સ્કોર:',
      'history_unknown_date': 'અજ્ઞાત તારીખ',
      'history_unknown_app': 'અજ્ઞાત એપ',
      'all_clear': 'બધું ક્લિયર',
      'all_clear_msg': 'આ ઓડિટમાં કોઈ શોષણખોર શરતો મળી નથી.',
      'share_title': '🛡️ LoanLens ગાર્ડિયન રિપોર્ટ',
    },
    'Kannada': {
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'language': 'ಭಾಷೆ',
      'namaste': 'ನಮಸ್ತೆ! \nನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
      'select_option': 'ಪ್ರಾರಂಭಿಸಲು ಕೆಳಗಿನ ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ.',
      'upload_photo': 'ಸಾಲದ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      'scan_subtitle': 'ಡಾಕ್ಯುಮೆಂಟ್ ಅಥವಾ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      'camera': 'ಕ್ಯಾಮರಾ',
      'gallery': 'ಗ್ಯಾಲರಿ',
      'speak_to_me': 'ನನ್ನೊಂದಿಗೆ ಮಾತನಾಡಿ',
      'speak_subtitle': 'ಧ್ವನಿ-ಸಹಾಯದ ಸಾಲದ ಆಡಿಟ್',
      'private_offline': 'ನಿಮ್ಮ ಡೇಟಾ ಖಾಸಗಿಯಾಗಿದೆ.',
      'analyzing': 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
      'error': 'ದೋಷ',
      'ok': 'ಸರಿ',
      'consent_title': 'ಡೇಟಾ ಹಂಚಿಕೊಳ್ಳಬೇಕೆ?',
      'consent_msg': 'ಇತರರನ್ನು ರಕ್ಷಿಸಲು, ನಾವು ಈ ಸಾಲವನ್ನು ಅನಾಮಧೇಯವಾಗಿ ರೆಕಾರ್ಡ್ ಮಾಡಬಹುದು.',
      'consent_no': 'ಇಲ್ಲ',
      'consent_yes': 'ಹೌದು',
      'btn_replay_audio': 'ಮರುಪ್ಲೇ ಮಾಡಿ',
      'error_network_title': 'ರಕ್ಷಕನ ಸಂಪರ್ಕ ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ',
      'error_network_msg': 'ವಿશ્ಲೇಷಣೆಗೆ ಅಂತರ್ಜಾಲದ ಅಗತ್ಯವಿದೆ.',
      'btn_retry': 'ಮತ್ತೆ ప్రయత్ಿಸಿ',
      'btn_home': 'ಮನೆ ಪುಟಕ್ಕೆ ಹೋಗಿ',
      'choose_language': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
      'guardian_active': 'ಗಾರ್ಡಿಯನ್ ಸಕ್ರಿಯವಾಗಿದೆ',
      'analyzing_caps': 'ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ',
      'listening': 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ...',
      'speak_now': 'ಈಗ ಮಾತನಾಡಿ...',
      'finish': 'ಮುಗಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'history_title': 'ದಾಖಲೆ',
      'history_empty_title': 'ದಾಖಲೆ ಸ್ಪಷ್ಟವಾಗಿದೆ',
      'history_empty_body': 'ಇನ್ನೂ ಯಾವುದೇ ಶೋಷಣೆಯ ದಾಖಲೆಗಳಿಲ್ಲ. ಮೊದಲ ಆಡಿಟ್ ಪ್ರಾರಂಭಿಸಿ!',
      'history_start_audit': 'ಮೊದಲ ಆಡಿಟ್ ಪ್ರಾರಂಭಿಸಿ',
      'history_bias': 'ಪಕ್ಷಪಾತದ ವಿಧ:',
      'history_deviation': 'ವಿಚಲನ:',
      'history_score_prefix': 'ಸ್ಕೋರ್:',
      'history_unknown_date': 'ಗೊತ್ತಿಲ್ಲದ ದಿನಾಂಕ',
      'history_unknown_app': 'ಗೊತ್ತಿಲ್ಲದ ಅಪ್ಲಿಕೇಶನ್',
      'all_clear': 'ಎಲ್ಲವೂ ಸರಿ ಇದೆ',
      'all_clear_msg': 'ಈ ಆಡಿಟ್‌ನಲ್ಲಿ ಯಾವುದೇ ಶೋಷಣೆಯ ನಿಯಮಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
      'share_title': '🛡️ LoanLens ಗಾರ್ಡಿಯನ್ ವರದಿ',
    },
    'Malayalam': {
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'language': 'ഭാഷ',
      'namaste': 'നമസ്കാരം! \nഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കാം?',
      'select_option': 'ആരംഭിക്കുന്നതിനായി താഴെ ഒരു ഓപ്ഷന്‍ തിരഞ്ഞെടുക്കുക.',
      'upload_photo': 'ലോൺ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
      'scan_subtitle': 'ഡോക്യുമെന്റ് അല്ലെങ്കിൽ സ്ക്രീൻഷോട്ട് സ്കാൻ ചെയ്യുക',
      'camera': 'ക്യാമറ',
      'gallery': 'ഗാലറി',
      'speak_to_me': 'എന്നോട് സംസാരിക്കുക',
      'speak_subtitle': 'വോയിസ്-എയ്ഡഡ് ലോൺ ഓഡിറ്റ്',
      'private_offline': 'നിങ്ങളുടെ ഡാറ്റ സ്വകാര്യമാണ്.',
      'analyzing': 'വിശകലനം ചെയ്യുന്നു...',
      'error': 'പിശക്',
      'ok': 'ശരി',
      'consent_title': 'ഡാറ്റ പങ്കിടണമോ?',
      'consent_msg': 'മറ്റുള്ളവരെ സംരക്ഷിക്കാൻ, ഞങ്ങൾ ഈ വായ്പ അജ്ഞാതമായി രേഖപ്പെടുത്തിയേക്കാം.',
      'consent_no': 'വേണ്ട',
      'consent_yes': 'അതെ',
      'btn_replay_audio': 'വീണ്ടും പ്ലേ ചെയ്യുക',
      'error_network_title': 'ഗാർഡിയനെ ബന്ധപ്പെടാൻ കഴിഞ്ഞില്ല',
      'error_network_msg': 'വിശകലനത്തിനായി ഇന്റർനെറ്റ് ആവശ്യമാണ്.',
      'btn_retry': 'വീണ്ടും ശ്രമിക്കുക',
      'btn_home': 'ഹോമിലേക്ക് പോകുക',
      'choose_language': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
      'guardian_active': 'ഗാർഡിയൻ സജീവമാണ്',
      'analyzing_caps': 'വിശകലനം ചെയ്യുന്നു',
      'listening': 'ശ്രദ്ധിക്കുന്നു...',
      'speak_now': 'ഇപ്പോൾ സംസാരിക്കു...',
      'finish': 'പൂർത്തിയാക്കുക',
      'cancel': 'റദ്ദാക്കുക',
      'history_title': 'റെക്കോർഡ്',
      'history_empty_title': 'റെക്കോർഡ് വ്യക്തമാണ്',
      'history_empty_body': 'ഇതുവരെ ചൂഷണ റെക്കോർഡുകളൊന്നുമില്ല. ആദ്യ ഓഡിറ്റ് ആരംഭിക്കൂ!',
      'history_start_audit': 'ആദ്യ ഓഡിറ്റ് ആരംഭിക്കുക',
      'history_bias': 'പക്ഷപാത തരം:',
      'history_deviation': 'വ്യതിയാനം:',
      'history_score_prefix': 'സ്കോർ:',
      'history_unknown_date': 'അജ്ഞാത തീയതി',
      'history_unknown_app': 'അജ്ഞാത ആപ്പ്',
      'all_clear': 'എല്ലാം വ്യക്തമാണ്',
      'all_clear_msg': 'ഈ ഓഡിറ്റിൽ ചൂഷണ നിബന്ധനകളൊന്നും കണ്ടെത്തിയില്ല.',
      'share_title': '🛡️ LoanLens ഗാർഡിയൻ റിപ്പോർട്ട്',
    },
    'Punjabi': {
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'language': 'ਭਾਸ਼ਾ',
      'namaste': 'ਨਮਸਤੇ! \nਮੈਂ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?',
      'select_option': 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਹੇਠਾਂ ਦਿੱਤਾ ਵਿਕਲਪ ਚੁਣੋ।',
      'upload_photo': 'ਲੋਨ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
      'scan_subtitle': 'ਦਸਤਾਵੇਜ਼ ਜਾਂ ਸਕ੍ਰੀਨਸ਼ਾਟ ਸਕੈਨ ਕਰੋ',
      'camera': 'ਕੈਮਰਾ',
      'gallery': 'ਗੈਲਰੀ',
      'speak_to_me': 'ਮੇਰੇ ਨਾਲ ਗੱਲ ਕਰੋ',
      'speak_subtitle': 'ਵੌਇਸ-ਏਡੇਡ ਲੋਨ ਆਡਿਟ',
      'private_offline': 'ਤੁਹਾਡਾ ਡੇਟਾ ਨਿੱਜੀ ਹੈ।',
      'analyzing': 'ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...',
      'error': 'ਗਲਤੀ',
      'ok': 'ਠੀਕ ਹੈ',
      'consent_title': 'ਡਾਟਾ ਸਾਂਝਾ ਕਰੀਏ?',
      'consent_msg': 'ਹੋਰਨਾਂ ਦੀ ਰੱਖਿਆ ਲਈ, ਅਸੀਂ ਇਸ ਨੂੰ ਅਗਿਆਤ ਰੂਪ ਵਿੱਚ ਰਿਕਾਰਡ ਕਰ ਸਕਦੇ ਹਾਂ।',
      'consent_no': 'ਨਹੀਂ',
      'consent_yes': 'ਹਾਂ',
      'btn_replay_audio': 'ਦੁਬਾਰਾ ਚਲਾਓ',
      'error_network_title': 'ਸਰਪ੍ਰਸਤ ਨਾਲ ਸੰਪਰਕ ਨਹੀਂ ਹੋ ਰਿਹਾ',
      'error_network_msg': 'ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਇੰਟਰਨੈਟ ਦੀ ਲੋੜ ਹੈ।',
      'btn_retry': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
      'btn_home': 'ਹੋਮ ਤੇ ਜਾਓ',
      'choose_language': 'अपनी भाषा चुणो',
      'guardian_active': 'ਸਰਪ੍ਰਸਤ ਸਰਗਰਮ ਹੈ',
      'analyzing_caps': 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ',
      'listening': 'ਸੁਣ ਰਿਹਾ ਹੈ...',
      'speak_now': 'ਹੁਣ ਬੋਲੋ...',
      'finish': 'ਖਤਮ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'history_title': 'ਰਿਕਾਰਡ',
      'history_empty_title': 'ਰਿਕਾਰਡ ਸਾਫ਼ ਹੈ',
      'history_empty_body': 'ਅਜੇ ਤੱਕ ਕੋਈ ਸ਼ੋਸ਼ਣ ਰਿਕਾਰਡ ਨਹੀਂ ਹੈ। ਪਹਿਲਾ ਆਡਿਟ ਸ਼ੁਰੂ ਕਰੋ!',
      'history_start_audit': 'ਪਹਿਲਾ ਆਡਿਟ ਸ਼ੁਰൂ ਕਰੋ',
      'history_bias': 'ਪੱਖਪਾਤ ਦੀ ਕਿਸਮ:',
      'history_deviation': 'ਵਿਚਲਨ:',
      'history_score_prefix': 'ਸਕੋਰ:',
      'history_unknown_date': 'ਅਣਜਾਣ ਮਿਤੀ',
      'history_unknown_app': 'ਅਣਜਾਣ ਐਪ',
      'all_clear': 'ਸਭ ਠੀਕ ਹੈ',
      'all_clear_msg': 'ਇਸ ਆਡਿਟ ਵਿੱਚ ਕੋਈ ਸ਼ੋਸ਼ਣ ਦੀਆਂ ਸ਼ਰਤਾਂ ਨਹੀਂ ਮਿਲੀਆਂ।',
      'share_title': '🛡️ LoanLens ਸਰਪ੍ਰਸਤ ਰਿਪੋਰਟ',
    },
    'Odia': {
      'select_language': 'ଭାଷା ବାଛନ୍ତୁ',
      'language': 'ଭાଷา',
      'namaste': 'ନମସ୍କାର! \nମୁଁ ଆପଣଙ୍କୁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?',
      'select_option': 'ଆରମ୍ଭ କରିବାକୁ ତଳେ ଥିବା ବିକଳ୍ପ ବାଛନ୍ତୁ.',
      'upload_photo': 'ଋଣ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ',
      'scan_subtitle': 'ଡକ୍ୟୁମେଣ୍ଟ୍ କିମ୍ବା ସ୍କ୍ରୀନସଟ୍ ସ୍କାନ୍ କରନ୍ତୁ',
      'camera': 'କ୍ୟାମେରା',
      'gallery': 'ଗ୍ୟାଲେରୀ',
      'speak_to_me': 'ମୋ ସହିତ କଥା ହୁଅନ୍ତୁ',
      'speak_subtitle': 'ଭଏସ୍-ଏଡେଡ୍ ଲୋନ୍ ଅଡିଟ୍',
      'private_offline': 'ଆପଣଙ୍କ ତଥ୍ୟ ବ୍ୟକ୍ତିଗତ.',
      'analyzing': 'ବିଶ୍ଳେଷଣ ଚାଲିଛି...',
      'error': 'ତ୍ରୁଟି',
      'ok': 'ଠିକ୍ ଅଛି',
      'consent_title': 'ଡାଟା ସେୟାର କରିବେ କି?',
      'consent_msg': 'ଅନ୍ୟମାନଙ୍କୁ ସୁରକ୍ଷା ଦେବା ପାଇଁ, ଆମେ ଅଜ୍ଞାତ ଭାବରେ ଏହାକୁ ରେକର୍ଡ କରିପାରିବୁ।',
      'consent_no': 'ନା',
      'consent_yes': 'ହଁ',
      'btn_replay_audio': 'ପୁନର୍ବାର ପ୍ଲେ କରନ୍ତୁ',
      'error_network_title': 'ଅଭିଭାବକଙ୍କ ସହିତ ଯୋગାଯୋଗ ହୋଇପାରିଲା ନାହିଁ',
      'error_network_msg': 'ବିଶ୍ଳେଷଣ ପାଇଁ ଇଣ୍ଟରନେଟ୍ ଆବଶ୍ୟକ |',
      'btn_retry': 'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ',
      'btn_home': 'ମୂଳ ପୃଷ୍ଠାକୁ ଯାଆନ୍ତୁ',
      'choose_language': 'ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ',
      'guardian_active': 'ଅଭିଭାବକ ସକ୍ରିୟ ଅଛନ୍ତି',
      'analyzing_caps': 'ବିଶ୍ଳେଷଣ କରୁଛି',
      'listening': 'ଶୁଣୁଛି...',
      'speak_now': 'ବର୍ତ୍તମାନ କୁହନ୍ତୁ...',
      'finish': 'ଶେଷ କରନ୍ତୁ',
      'cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
      'history_title': 'ରେକର୍ଡ',
      'history_empty_title': 'ରେକର୍ଡ ସ୍ପଷ୍ଟ ଅଛି',
      'history_empty_body': 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଶୋଷଣକାରୀ ରେକର୍ଡ ନାହିଁ। ପ୍ରଥମ ଅଡିਟ୍ ଆରମ୍ଭ କରନ୍ତୁ!',
      'history_start_audit': 'ପ୍ରଥମ ଅଡିਟ୍ ଆରମ୍ଭ କରନ୍ତୁ',
      'history_bias': 'ପକ୍ଷපାତ ପ୍ରକାର:',
      'history_deviation': 'ବିଚ୍ୟୁତି:',
      'history_score_prefix': 'ସ୍କୋର:',
      'history_unknown_date': 'ଅଜ୍ଞାତ ତାରିଖ',
      'history_unknown_app': 'ଅଜ୍ଞାତ ଆପ୍',
      'all_clear': 'ସବು ସଫା',
      'all_clear_msg': 'ଏହି ଅଡିଟ୍‌ରେ କୌଣସି ଶୋଷଣମୂଳକ ସର୍ତ୍ତ ମିଳିଲା ନାହିଁ।',
      'share_title': '🛡️ LoanLens ଅଭିଭାବକ ରିපୋର୍ଟ',
    },
  };
}
